AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket and cloudfront distribution.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: DEV1

Resources:
  webPage:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Solution
          Value: s3-web
  SampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref webPage
      PolicyDocument:
        Version: 2012-10-17
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref webPage
                - /*
            Principal:
              Service:
                - 'cloudfront.amazonaws.com'
            Condition:
              StringEquals:
                'AWS:SourceArn':
                  - 'arn:aws:cloudfront::629161408027:distribution/EBHU232M686WV'

Outputs:
  bucketWebPage:
    Description: The bucket name that contains the web site
    Value: !Ref webPage
    Export:
      Name: !Sub "${EnvironmentName}-bucketName"