AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket and cloudfront distribution.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: DEV1

Resources:
  myControlAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "Access CDN to S3"
        Name: "s3 access"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: no-override
        SigningProtocol: sigv4

  myDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Sub "${webPage}.s3.amazonaws.com"
          Id: myS3Origin
          S3OriginConfig:
            # OriginAccessIdentity: !Join [ "/", [ 'origin-access-identity/cloudfront', !GetAtt myControlAccess.Id ]]
            OriginAccessIdentity: origin-access-identity/cloudfront/EGPVKFD94VKHU
        Enabled: 'true'
        Comment: Some comment
        DefaultRootObject: index.html
        Aliases:
        - aws.netsys.uno
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          TrustedSigners:
          - !Ref AWS::AccountId
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'

Outputs:
  bucketWebPage:
    Description: The bucket name that contains the web site
    Value: !Ref webPage
    Export:
      Name: !Sub "${EnvironmentName}-bucketName"