AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This stack deploy All private ec2 infrastructure for alex

Parameters:
  InstanceTypeParameter:
    Description: Enter t2.micro just it its free.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  appserver01:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-0dfcb1ef8550277af"
      KeyName: "netsys"
      InstanceType: !Ref InstanceTypeParameter
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-appserver01
      SecurityGroupIds: 
        - Ref: SecurityGroupSSH
      SubnetId: !Select [ "0", !Split [ ",", !ImportValue VpcPrivateSubnets ] ]

  appserver02:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-0dfcb1ef8550277af"
      KeyName: "netsys"
      InstanceType: !Ref InstanceTypeParameter
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-appserver02
      SecurityGroupIds: 
        - Ref: SecurityGroupSSH
      SubnetId: !Select [ "1", !Split [ ",", !ImportValue VpcPrivateSubnets ] ]

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-securityGroup-private
      GroupDescription: "Security group que permite acceso ssh"
      VpcId: !ImportValue MyVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0         
  