AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This stack deploy All infrastructure for alex

Parameters:
  InstanceTypeParameter:
    Description: Enter t2.micro just it its free.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro

Resources:
  WebServer:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: "ami-0dfcb1ef8550277af"
      KeyName: "netsys"
      InstanceType: !Ref InstanceTypeParameter
      Tags:
        - Key: Name
          Value: PublicVm01
      SecurityGroupIds: 
        - Ref: SecurityGroupSSH
      SubnetId: !Select [ "0", !Split [ ",", !ImportValue VpcPublicSubnets ] ]

  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group que permite acceso ssh"
      VpcId: !ImportValue MyVpcId

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 191.92.17.213/32
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0         
  