AWSTemplateFormatVersion: "2010-09-09"
Description: >
  this cloudformation stack creates a iam user and group then assing policy to the group.

Parameters:
  UserName:
    Type: String
    Description: Enter the name of the IAM user.
    Default: "IamUser"


Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile: 
        Password: Dude.123
        PasswordResetRequired: true
      Tags:
        - Key: by
          Value: Cloudformation