AWSTemplateFormatVersion: "2010-09-09"
Description: S3 Bucket and cloudfront distribution.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: DEV1

Resources:
  bucketPage:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Solution
          Value: s3-web

  cdnS3ControlAccess:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "Access CDN to S3 bucket"
        Name: "controlAccessBucket"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: no-override
        SigningProtocol: sigv4

  s3Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !GetAtt bucketPage.RegionalDomainName
          Id: myS3Origin
          OriginAccessControlId: !Ref cdnS3ControlAccess
          S3OriginConfig: 
            OriginAccessIdentity: ''
        Enabled: 'true'
        Comment: Distribution to serve a web site allocated on a bucket
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_All

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref bucketPage
      PolicyDocument:
        Version: 2012-10-17
        Id: PolicyForCloudFrontPrivateContent
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref bucketPage
                - /*
            Principal:
              Service:
                - 'cloudfront.amazonaws.com'
            Condition:
              StringEquals:
                'AWS:SourceArn':
                  - !Join ["", ["arn:aws:cloudfront::", !Ref AWS::AccountId ,":distribution/", !GetAtt s3Distribution.Id]]

Outputs:
  bucketName:
    Description: The bucket name that contains the web site
    Value: !Ref bucketPage
    Export:
      Name: !Sub "${EnvironmentName}-bucketName"
  cdnDomain:
    Description: The cdn domain to acces.
    Value: !GetAtt s3Distribution.DomainName
    Export:
      Name: !Sub "${EnvironmentName}-cdnDomain"
