Metadata:
Resources:
  publicvm01:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0dfcb1ef8550277af
      InstanceType: t2.micro
      # SubnetId: subnet-0f9131c7916bcd57f
      SecurityGroups:
        - Ref: publicsg
      KeyName: netsys
      Tags:
        - Key: Name
          Value: publicvm01
    Metadata:
      "AWS::CloudFormation::Designer":
        id: 23682bc1-1bc4-4f06-a542-fac766f27e8b
  publicsg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow connection to ssh
      GroupName: management
      SecurityGroupEgress:
        - Egress
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Permit ssh
          FromPort: -1
          IpProtocol: tcp
          ToPort: 22
      Tags:
        - Key: by
          Value: cloudformation
      VpcId: vpc-0fe67db848648ddab
