AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster

  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-ecs-task
      ContainerDefinitions:
        - Name: my-container
          Image: nginx:latest
          PortMappings:
            - ContainerPort: 80
          Memory: 512  # Puedes ajustar este valor según tus necesidades

  EcsService:
    Type: AWS::ECS::Service
    DependsOn: ECSCluster
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref EcsTaskDefinition
